baseURL = "http://wedgevine.github.io/house/"
languageCode = "en-us"
title = "house"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  # themeVariant = "green"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
